name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js and pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm' # Add this line to enable caching of pnpm dependencies
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout gh-pages
          mv dist/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -u origin gh-pages
